language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
      - tobydox/mingw-x-precise
    packages:
      - cmake
      - cmake-data
      - g++-5
      - gcc-5
      - mingw-w64
      - g++-mingw-w64

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - mkdir build && cd build && cmake .. && make && make test && cd ..
  - mkdir build_win && cd build_win && cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/Toolchain-Ubuntu-mingw64.cmake && make && cd ..
