language: cpp
dist: trusty
sudo: required
os:
  - linux
  - osx
before_install:
  - sh setup_travis_linux.sh

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
- mkdir build && cd build && cmake .. && make && make test && cd ..
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build_win && cd build_win && cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/Toolchain-mingw64.cmake
  && make && cd ..; fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kRge09+v5vq6dXoKyQ21kHSPYPHQnwtaRUV5UqMY2vd4f0WoWMqQfKbqwe62OzpE0mzbpgQEWd7FeoScg9TuFcsGzbcfv/9YIRVOSMxjLlhQJsxzc1n4n/N5YdX70OzCw8U2/xTzusdyz8kaMQ5sieX+AHtQuHrAo0yhNh2VnGWHwoRJ2As1UaSxyO6P3Tt2OGtx75oNsdQ26dUinuWtyI7w6l5UDtx43okK3f0rU/ARawL9Nst8Ut6xNy9MDmR7/B4I1opmsAkZBZG/ic8F0uo2TaNHUEZbH9/7s0VoRVDtJ04ueE86eTmzlaiExg9t1aJPHx9s7CFvFlx+sOqbqckayke0WklFCMWPFudY5dDmtDnoBtKedfXIyncQn8UH1LiXzzIj5e2Ji9qoENDefAnCv0uHDMu7LoGVnNfxwJkP20gZ60Yf1xAK++gj98N+mE445Ww4TcyJVB78v7hEhch3j1yDuz2bVqTdTS0iqWTvK8YScktzAX+d1YBtsygtqjzAgJ2tuK02if4/00rveLj/R2y55hn56lnB7fZ9I+tPhMVj797qALun/uOY+zcikNRvgJOFuKHAGCP45qle/LwUm7RK5cu4XpiPEDpW7psvP+L3fiaeHesMAsCI3Xv7DrQXT1JYHI8qWLaUmDhypMTHmKG3MMcKU5nb3h89G14=
  file:
    - build_win/bin/libledger-core.dll
    - build/bin/libledger-core.so
  on:
    repo: tag
