language: cpp
dist: trusty
sudo: required

before_install:
 - echo "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted multiverse universe" | cat - /etc/apt/source.list | sudo tee /etc/apt/source.list
 - sudo apt-get update
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update
 - sudo apt-get -y install gcc-5 g++-5
 - sudo apt-get -y install mingw-w64

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - mkdir build && cd build && cmake .. && make && make test && cd ..
  - mkdir build_win && cd build_win && cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/Toolchain-mingw64.cmake && make && cd ..
